# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56bfc106707963ffafeda4133530a1f420e04b1a0a3b9dd2aa9015493257f80457a1c85aedd7d8342654fabd8ea448382bd6e7c810d3ee741edb77e767bcce1

test:
  secret_key_base: 20cfcabcc87ba49bec4ce1d55574de7312bc3db636e528701ce0e7b2940cf6d3d8e51fd42370b10068931891f31244dad32097536e3eaf012c10399265fcb7d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
